//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymFit.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notatka
    {
        public int Id { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public string Tytuł { get; set; }
        public string Notatka1 { get; set; }
        public bool CzyAktywna { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> IdPracownikaDodajacego { get; set; }
        public Nullable<System.DateTime> DataCzasDodania { get; set; }
        public Nullable<int> IdPracownikaModyfikujacego { get; set; }
        public Nullable<System.DateTime> DataCzasModyfikacji { get; set; }
        public Nullable<int> IdPracownikaKasujacego { get; set; }
        public Nullable<System.DateTime> DataCzasSkasowania { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
    }
}
